ALTER TABLE IF EXISTS "booking_payments"
ADD COLUMN IF NOT EXISTS "convenience_fee_rate" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "convenience_fee_amount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "total_payable_online" INTEGER NOT NULL DEFAULT 0;
